services:
  work-order-service:
    build:
      context: ../../../
      dockerfile: deploy/Server/work-order-service/Dockerfile
    container_name: emaintenance-work-order-service
    ports:
      - "${WORK_ORDER_SERVICE_PORT:-3002}:3002"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@emaintenance-postgres:5432/emaintenance
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL:-redis://emaintenance-redis:6379}
      - USER_SERVICE_URL=${USER_SERVICE_URL:-http://emaintenance-user-service:3001}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - /opt/emaintenance/logs/work-order-service:/app/logs
      - /opt/emaintenance/data/work-order-uploads:/app/uploads
    networks:
      - emaintenance-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  emaintenance-network:
    external: true